# alpine + nginx + dokuwiki

# usage:
# => 0. run `vagrant up` to provision
# => 1. add or symlink existing dokuwiki pages (if any) to ./pages
# => 2. direct your browser to http://localhost:8080/install.php to install

# WARNING: this dokuwiki installation is for *local use*, do not
#+ host this box anywhere where it can be accessed from the
#+ internet without thoroughly configuring nginx & dokuwiki
#+ with security in mind, see:
# => https://www.dokuwiki.org/install:permissions
# => https://www.dokuwiki.org/security

$script = <<-SCRIPT
apk update \
	&& apk add nginx php7 php7-gd php7-fpm php7-xml php7-session php7-json \
	&& sed -i \
		-e 's/^;\?\s*user\s*=.*/user = nginx/' \
		-e 's/^;\?\s*group\s*=.*/group = nginx/' \
		-e 's/^;\?\s*listen\s*=.*/listen = \/var\/run\/php-fpm7\/php.sock/' \
		-e 's/^;\?\s*listen\.owner\s*=.*/listen.owner = nginx/' \
		-e 's/^;\?\s*listen\.group\s*=.*/listen.group = nginx/' \
		-e 's/^;\?\s*listen\.mode\s*=.*/listen.mode = 0600/' \
		/etc/php7/php-fpm.d/www.conf \
	&& rc-update add php-fpm7 \
	&& rc-update add nginx \
	&& cat > /etc/nginx/conf.d/dokuwiki.conf <<'EOF'
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/localhost/htdocs/dokuwiki;
	index doku.php;

	location ~ ^/lib.*\.(js|css|gif|png|ico|jpg|jpeg)$ {
		expires 365d;
	}

	location / { try_files $uri $uri/ @dokuwiki; }

	location @dokuwiki {
		rewrite ^/_media/(.*) /lib/exe/fetch.php?media=$1 last;
		rewrite ^/_detail/(.*) /lib/exe/detail.php?media=$1 last;
		rewrite ^/_export/([^/]+)/(.*) /doku.php?do=export_$1&id=$2 last;
		rewrite ^/(.*) /doku.php?id=$1&$args last;
	}

	location ~ \.php$ {
        	try_files $uri $uri/ /doku.php;
	        include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param REDIRECT_STATUS 200;
		fastcgi_pass unix:/var/run/php-fpm7/php.sock;
	}
EOF

cd /var/www/localhost/htdocs \
	&& wget -O dokuwiki.tgz https://download.dokuwiki.org/src/dokuwiki/dokuwiki-rc.tgz \
	&& tar zxvf dokuwiki.tgz \
	&& rm dokuwiki.tgz \
	&& mv dokuwiki*/ dokuwiki

cd /var/www/localhost/htdocs/dokuwiki/lib/tpl \
	&& wget -O bs3-template.tar https://github.com/LotarProject/dokuwiki-template-bootstrap3/tarball/master \
	&& tar xvf bs3-template.tar \
	&& rm bs3-template.tar \
	&& mv *dokuwiki-template*/ bootstrap3 \
	&& cat > ../../conf/local.php <<'EOF'
$conf['template'] = 'bootstrap3'
EOF

chown -R nginx:nginx /var/www/localhost/htdocs/dokuwiki \
	&& chmod -R 700 /var/www/localhost/htdocs/dokuwiki
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.provision "shell", inline: $script
  #config.vm.synced_folder "pages/", "/var/www/localhost/htdocs/dokuwiki/data/pages", owner: "nginx", group: "nginx"
  config.vm.network "forwarded_port", guest: 80, host:8081
end
